version: "2"
services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=supersecret
      - MYSQL_DATABASE=systelab
      - MYSQL_USER=systelab
      - MYSQL_PASSWORD=systelab
  backend1:
    image: patientservice:1.0
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=systelab
      - DB_USER=systelab
      - DB_PASSWORD=systelab