INSERT INTO systelab.Patient(ID,FIRST_NAME,LAST_NAME,START_DATE,AGE,STATUS) VALUES(10,'JOHN','DOE','2016-01-01',30,'ACTIVE');
INSERT INTO systelab.Patient(ID,FIRST_NAME,LAST_NAME,START_DATE,AGE,STATUS) values(20,'JANE','DOE','2015-10-01',33,'ACTIVE');
INSERT INTO systelab.Patient(ID,FIRST_NAME,LAST_NAME,START_DATE,AGE,STATUS) values(30,'DUKE','DOE','1995-06-01',23,'ACTIVE');
